[features]
seeds = false
skip-lint = false

[programs.localnet]
masterarbeit_philipp_roiner = "5C4WbaLJTN1q7UiUAcC3yYttbEHK6AUvFoopzeDhmMj9"

[programs.devnet]
masterarbeit_philipp_roiner = "5C4WbaLJTN1q7UiUAcC3yYttbEHK6AUvFoopzeDhmMj9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/philipproiner/.config/solana/id4.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
