[features]
seeds = false
skip-lint = false

[programs.localnet]
masterarbeit_philipp_roiner = "FhKv5xKBKppK18jRDwAcXtpmALWzqppGkW2sPZ578YqQ"

[programs.devnet]
masterarbeit_philipp_roiner = "FhKv5xKBKppK18jRDwAcXtpmALWzqppGkW2sPZ578YqQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/philipproiner/.config/solana/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
