version: '3.8'
services:
  app:
    build: ./app
    ports:
      - "8081:8081"
    volumes:
      - /Users/philipproiner/Documents/development/masterarbeit/masterarbeit_philipp_roiner/app:/app
      - /app/node_modules
    env_file:
      - ./app/.env.devnet
  server: 
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - /Users/philipproiner/Documents/development/masterarbeit/masterarbeit_philipp_roiner/server:/server
      - /app/node_modules